import type { Metadata } from "next";
import { BioRhyme } from "next/font/google";
import "./globals.css";
import Fab from '@/components/atoms/fab';

const sora = BioRhyme({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sora.className} flex flex-col justify-between h-screen`}>
        <div>
          {children}
        </div>
        <div className = "fixed left-0 bottom-0 w-full">
          <Fab />
        </div>
      </body>
    </html>
  );
}
